### ISSUE TITLE
introduce report_data spreadsheets

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/spreadsheets-socialsci#32]
Describe data being used for report_data_c.xlsx and report_data_o.xlsx

What is the "Reading" variable and what units is it in? 
Where are "North" and "South" regions of?
Is this modified from real data that is available somewhere?

These questions should be answered when the data is first introduced.

**Comment by PeterSmyth12** [comment]
Replace 
-----------
In this episode we are going to look a spreadsheet which has been designed as if it was to be a printed report rather than a single data table. We will highlight the problems with the layout and then provide instructions on how it might be changed to be more usable for analysis.

The spreadsheet can be downloaded from here.

The problems that we can see are as follows:

    White space to the top and to the left of the data.
    There are two header line types with different data items in each
    One of the header line has two separate data items

What we want is a spreadsheet which looks more like this.

----------------------------------------------------------
With this
---------------------------
In this episode we are going to look at a fictional spreadsheet with randomly generated data for the Readings column for the North and South regional offices for a ficticious company. For the purposes of this exercise it is not the data itself that is important, but how it has been formatted. The spreadsheet has been designed as if it was to be a printed report rather than a single data table.


We will highlight the problems with the layout and then provide instructions on how it might be changed to be more usable for analysis.

The spreadsheet can be downloaded from here.

The problems that we can see are as follows:

    White space to the top and to the left of the data.
    There are two header line types with different data items in each
    One of the header line has two separate data items

What we want is a spreadsheet which looks more like this.

**Comment by ErinBecker** [comment]
Closed in favor of solution proposed in #37.
