### ISSUE TITLE
They key points for Episode 2 are unclear

### ISSUE THREAD

**Issue by sechilds** [datacarpentry/spreadsheets-socialsci#35]
The text for Episode 2's key points is a bit unclear:

>Heading lines may contain information relevant to the rows below it and needs to added to each of them.
>There may be multiple heading lines with different information in each.

I saw this when I was reviewing #34 

For the first point, we are referring to plural and singular heading lines in the same sentence.

**Comment by ErinBecker** [comment]
Thanks @sechilds. The keypoints for all of the episodes have been updated in the past week or so. Episode 2 keypoints are now: 

- "Avoid using multiple tables within one spreadsheet."
- "Avoid spreading data across multiple tabs (but do use a new tab to record data cleaning or manipulations)."
- "Record zeros as zeros."
- "Use an appropriate null value to record missing data."
- "Don't use formatting to convey information or to make your spreadsheet look pretty."
- "Place comments in a separate column."
- "Record units in column headers."
- "Include only one piece of information in a cell."
- "Avoid spaces, numbers and special characters in column headers."
- "Avoid special characters in your data."

Since header lines are no longer mentioned, closing this issue.
