### ISSUE TITLE
Simplify installation instructions for libreoffice

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/spreadsheets-socialsci#45]
they are exactly repeated for the 3 OSes

**Comment by ErinBecker** [comment]
This is intentional. My understanding is that the instructions are set up this way in general for cases where there *are* differences in install between the three systems. This is also how things are formatted in the [spreadsheets ecology lesson](http://www.datacarpentry.org/spreadsheet-ecology-lesson/setup/). I will mark this as "out of scope" for now as it seems to me more of a general formatting issue (across lessons) than something that needs to be fixed in one particular lesson.
